"""Animate one simulated leg through Reference and validation rounds C1–C3.

The figure is a kinematic rendering of the frozen offline trajectories.  The
second segment ends at the model's L2 distal traction/strap-equivalent point;
it is not presented as an anatomical ankle.  No policy, simulation outcome, or
robot command is generated by this visualization.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
from pathlib import Path
import tempfile
from typing import Any, Mapping, Sequence

_MPL_CACHE = Path(tempfile.gettempdir()) / "rehab_robot_matplotlib_cache"
_MPL_CACHE.mkdir(parents=True, exist_ok=True)
os.environ.setdefault("MPLCONFIGDIR", str(_MPL_CACHE))

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib import patches
import numpy as np
from PIL import Image

from .generate_final_method_animation import (
    _BLUE,
    _DARK,
    _GRAY,
    _GREEN,
    _LIGHT,
    _ORANGE,
    _RED,
    _style,
)
from .generate_single_subject_end_to_end_animation import (
    DEFAULT_CASE_ID,
    DEFAULT_OUTPUT_DIRECTORY,
    SOURCE_ARTIFACT_DIRECTORY,
    _atomic_bytes,
    _load_case,
    _sha256,
)


GIF_NAME = "SUPINE_PATIENT_HIP_KNEE_FLEXION_ROUNDS.gif"
METADATA_NAME = "supine_leg_motion_metadata.json"
GUIDE_NAME = "SUPINE_LEG_ANIMATION_README.md"
DEFAULT_SAMPLES_PER_ROUND = 41

_ROUND_COLORS = {
    "Reference": _GRAY,
    "C1": _GREEN,
    "C2": _BLUE,
    "C3": _ORANGE,
}


def _global_ranges(trajectories: Mapping[str, Any]) -> dict[str, tuple[float, float]]:
    values: dict[str, list[np.ndarray]] = {
        "x": [],
        "z": [],
        "q_hip": [],
        "q_knee": [],
    }
    for trajectory in trajectories.values():
        values["x"].extend(
            [
                trajectory["x_knee_m"].to_numpy(dtype=float),
                trajectory["x_pull_m"].to_numpy(dtype=float),
            ]
        )
        values["z"].extend(
            [
                trajectory["z_knee_m"].to_numpy(dtype=float),
                trajectory["z_pull_m"].to_numpy(dtype=float),
            ]
        )
        values["q_hip"].append(np.rad2deg(trajectory["q_hip_rad"].to_numpy(dtype=float)))
        values["q_knee"].append(np.rad2deg(trajectory["q_knee_rad"].to_numpy(dtype=float)))
    output: dict[str, tuple[float, float]] = {}
    for key, arrays in values.items():
        joined = np.concatenate(arrays)
        output[key] = (float(np.min(joined)), float(np.max(joined)))
    return output


def _round_records(data: Mapping[str, Any]) -> list[dict[str, Any]]:
    records: list[dict[str, Any]] = [
        {
            "round": 0,
            "label": "Reference",
            "trajectory": data["trajectories"]["Reference"],
            "alpha": (0.0, 0.0, 0.0),
            "J_pred": None,
            "J_actual": 1.0,
            "best_J": 1.0,
            "best_label": "Reference",
        }
    ]
    for row in data["execution"].itertuples(index=False):
        records.append(
            {
                "round": int(row.round),
                "label": str(row.candidate_id),
                "trajectory": data["trajectories"][str(row.candidate_id)],
                "alpha": (float(row.hip_delta), float(row.knee_delta), float(row.phase_delta)),
                "J_pred": float(row.J_pred_before_execution),
                "J_actual": float(row.actual_J),
                "best_J": float(row.best_validated_J_after),
                "best_label": (
                    "Reference"
                    if str(row.best_validated_trajectory_id_after).startswith("reference_")
                    else str(
                        data["execution"]
                        .set_index("trajectory_id")
                        .loc[str(row.best_validated_trajectory_id_after), "candidate_id"]
                    )
                ),
            }
        )
    return records


def _draw_timeline(axis: plt.Axes, active_round: int) -> None:
    axis.set_xlim(0, 4)
    axis.set_ylim(0, 1)
    axis.axis("off")
    labels = ("Round 0\nReference", "Round 1\nC1", "Round 2\nC2", "Round 3\nC3")
    for index, label in enumerate(labels):
        color = _ROUND_COLORS[("Reference", "C1", "C2", "C3")[index]]
        completed = index <= active_round
        rectangle = patches.FancyBboxPatch(
            (index + 0.06, 0.13),
            0.80,
            0.68,
            boxstyle="round,pad=0.01,rounding_size=0.035",
            facecolor=color if completed else "white",
            edgecolor=color,
            linewidth=1.6,
            alpha=0.92 if completed else 0.55,
        )
        axis.add_patch(rectangle)
        axis.text(
            index + 0.46,
            0.47,
            label,
            ha="center",
            va="center",
            fontsize=9,
            weight="bold" if index == active_round else "normal",
            color="white" if completed else _GRAY,
        )
        if index < 3:
            axis.annotate(
                "",
                xy=(index + 1.03, 0.47),
                xytext=(index + 0.88, 0.47),
                arrowprops={"arrowstyle": "-|>", "color": _GRAY, "lw": 1.2},
            )


def _draw_leg(
    axis: plt.Axes,
    record: Mapping[str, Any],
    reference: Any,
    sample_index: int,
    ranges: Mapping[str, tuple[float, float]],
) -> None:
    trajectory = record["trajectory"]
    _, x_max = ranges["x"]
    _, z_max = ranges["z"]
    axis.set_xlim(-1.02, max(0.82, x_max + 0.13))
    axis.set_ylim(-0.20, z_max + 0.15)
    axis.set_aspect("equal", adjustable="box")
    axis.set_xlabel("Horizontal position along bed x (m)")
    axis.set_ylabel("Height above bed z (m)")
    axis.set_title("Supine hip–knee flexion", fontsize=14, weight="bold")
    axis.grid(True, color="#E6EBF0", lw=0.7)

    # Fixed bed and torso are orientation cues; animated data begin at the hip.
    mattress = patches.FancyBboxPatch(
        (-0.98, -0.115),
        1.80,
        0.085,
        boxstyle="round,pad=0.01,rounding_size=0.018",
        facecolor="#DDEAF4",
        edgecolor="#7D95A8",
        linewidth=1.6,
        zorder=0,
    )
    axis.add_patch(mattress)
    axis.plot([-0.91, -0.91], [-0.12, -0.18], color="#7D95A8", lw=4)
    axis.plot([0.74, 0.74], [-0.12, -0.18], color="#7D95A8", lw=4)
    pillow = patches.FancyBboxPatch(
        (-0.93, -0.005),
        0.34,
        0.105,
        boxstyle="round,pad=0.01,rounding_size=0.035",
        facecolor="white",
        edgecolor="#AAB9C5",
        linewidth=1.2,
        zorder=1,
    )
    axis.add_patch(pillow)
    skin = "#D9A07E"
    axis.add_patch(
        patches.Circle(
            (-0.72, 0.105),
            0.052,
            facecolor=skin,
            edgecolor=_DARK,
            lw=1.5,
            zorder=3,
        )
    )
    axis.plot(
        [-0.66, -0.08],
        [0.045, 0.015],
        color=_DARK,
        lw=18,
        solid_capstyle="round",
        zorder=2,
    )
    axis.plot(
        [-0.50, -0.16],
        [0.035, 0.105],
        color=skin,
        lw=7,
        solid_capstyle="round",
        zorder=3,
    )
    axis.plot(
        [-0.08, 0.0],
        [0.015, 0.0],
        color=skin,
        lw=15,
        solid_capstyle="round",
        zorder=3,
    )
    axis.text(-0.88, -0.165, "Hospital bed (schematic)", fontsize=8.5, color=_GRAY)

    current_color = _ROUND_COLORS[str(record["label"])]
    if int(record["round"]) > 0:
        reference_index = min(sample_index, len(reference) - 1)
        ref_knee = (
            float(reference.iloc[reference_index]["x_knee_m"]),
            float(reference.iloc[reference_index]["z_knee_m"]),
        )
        ref_pull = (
            float(reference.iloc[reference_index]["x_pull_m"]),
            float(reference.iloc[reference_index]["z_pull_m"]),
        )
        axis.plot(
            [0.0, ref_knee[0], ref_pull[0]],
            [0.0, ref_knee[1], ref_pull[1]],
            "--",
            color=_GRAY,
            lw=4,
            alpha=0.42,
            label="Reference pose at same time",
        )

    knee = (
        float(trajectory.iloc[sample_index]["x_knee_m"]),
        float(trajectory.iloc[sample_index]["z_knee_m"]),
    )
    pull = (
        float(trajectory.iloc[sample_index]["x_pull_m"]),
        float(trajectory.iloc[sample_index]["z_pull_m"]),
    )
    axis.plot(
        trajectory["x_pull_m"],
        trajectory["z_pull_m"],
        color=current_color,
        lw=1.2,
        alpha=0.20,
        label="Full distal-point path",
    )
    axis.plot(
        trajectory["x_pull_m"].iloc[: sample_index + 1],
        trajectory["z_pull_m"].iloc[: sample_index + 1],
        color=current_color,
        lw=2.6,
        alpha=0.80,
        label="Path completed",
    )
    axis.plot(
        [0.0, knee[0]],
        [0.0, knee[1]],
        color=skin,
        lw=18,
        solid_capstyle="round",
        zorder=3,
    )
    axis.plot(
        [0.0, knee[0]],
        [0.0, knee[1]],
        color=_BLUE,
        lw=9,
        solid_capstyle="round",
        zorder=4,
    )
    axis.plot(
        [knee[0], pull[0]],
        [knee[1], pull[1]],
        color=skin,
        lw=16,
        solid_capstyle="round",
        zorder=3,
    )
    axis.plot(
        [knee[0], pull[0]],
        [knee[1], pull[1]],
        color=_ORANGE,
        lw=8,
        solid_capstyle="round",
        zorder=4,
    )
    axis.scatter([0.0], [0.0], s=150, color=_DARK, edgecolor="white", lw=1.5, zorder=5)
    axis.scatter([knee[0]], [knee[1]], s=145, color="white", edgecolor=_DARK, lw=2.4, zorder=5)
    axis.scatter([pull[0]], [pull[1]], s=125, color=current_color, edgecolor="white", lw=1.8, zorder=5)
    axis.annotate("Hip", (0.0, 0.0), xytext=(-24, 8), textcoords="offset points", fontsize=9)
    axis.annotate("Knee", knee, xytext=(-8, 10), textcoords="offset points", fontsize=9)
    axis.annotate(
        "Distal strap/traction point (L2)",
        pull,
        xytext=(8, 7),
        textcoords="offset points",
        fontsize=9,
        color=current_color,
    )
    axis.legend(frameon=False, fontsize=8, loc="lower left")


def _draw_angle_panel(
    axis: plt.Axes,
    trajectory: Any,
    reference: Any,
    sample_index: int,
    column: str,
    title: str,
    current_color: str,
    y_range: tuple[float, float],
    show_reference: bool,
) -> None:
    time_s = trajectory["time_s"].to_numpy(dtype=float)
    values = np.rad2deg(trajectory[column].to_numpy(dtype=float))
    if show_reference:
        axis.plot(
            reference["time_s"],
            np.rad2deg(reference[column]),
            color=_GRAY,
            ls="--",
            lw=1.5,
            alpha=0.65,
            label="Reference",
        )
    axis.plot(time_s, values, color=current_color, lw=2.4, label="Current round")
    axis.axvline(time_s[sample_index], color=_RED, lw=1.5, alpha=0.75)
    axis.scatter([time_s[sample_index]], [values[sample_index]], s=55, color=current_color, edgecolor="white", lw=1.2, zorder=5)
    padding = max(2.5, 0.08 * (y_range[1] - y_range[0]))
    axis.set_ylim(y_range[0] - padding, y_range[1] + padding)
    axis.set_xlim(float(time_s.min()), float(time_s.max()))
    axis.set_ylabel("Angle (deg)")
    axis.set_title(f"{title}: {values[sample_index]:.1f}°", fontsize=12)
    axis.grid(True, color="#E6EBF0", lw=0.7)
    axis.legend(frameon=False, fontsize=8, loc="best")


def _render_motion_frame(
    data: Mapping[str, Any],
    record: Mapping[str, Any],
    sample_index: int,
    ranges: Mapping[str, tuple[float, float]],
) -> Image.Image:
    subject = data["subject"]
    trajectory = record["trajectory"]
    reference = data["trajectories"]["Reference"]
    color = _ROUND_COLORS[str(record["label"])]
    figure = plt.figure(figsize=(12.8, 7.2), dpi=100, facecolor="white")
    figure.text(
        0.04,
        0.965,
        f"SUPINE PATIENT — HIP/KNEE FLEXION — ROUND {record['round']}: {record['label']}",
        fontsize=19,
        weight="bold",
        color=_DARK,
        va="top",
    )
    time_s = float(trajectory.iloc[sample_index]["time_s"])
    figure.text(
        0.96,
        0.962,
        f"cycle time {time_s:5.2f} / 24.00 s",
        fontsize=12,
        color=color,
        ha="right",
        va="top",
    )
    leg_axis = figure.add_axes((0.055, 0.17, 0.51, 0.71))
    hip_axis = figure.add_axes((0.64, 0.56, 0.32, 0.27))
    knee_axis = figure.add_axes((0.64, 0.21, 0.32, 0.27), sharex=hip_axis)
    timeline_axis = figure.add_axes((0.12, 0.045, 0.76, 0.085))
    _draw_leg(leg_axis, record, reference, sample_index, ranges)
    _draw_angle_panel(
        hip_axis,
        trajectory,
        reference,
        sample_index,
        "q_hip_rad",
        "Hip flexion",
        color,
        ranges["q_hip"],
        int(record["round"]) > 0,
    )
    _draw_angle_panel(
        knee_axis,
        trajectory,
        reference,
        sample_index,
        "q_knee_rad",
        "Knee flexion",
        color,
        ranges["q_knee"],
        int(record["round"]) > 0,
    )
    knee_axis.set_xlabel("Time in complete trajectory (s)")
    plt.setp(hip_axis.get_xticklabels(), visible=False)
    _draw_timeline(timeline_axis, int(record["round"]))

    hip, knee, phase = record["alpha"]
    if int(record["round"]) == 0:
        metric = "Reference: α=(0, 0, 0)   measured/virtual-truth J=1.000000"
    else:
        metric = (
            f"α=({hip:+.2f}°, {knee:+.2f}°, {phase:+.4f})   "
            f"Jpred={record['J_pred']:.6f}   Jtruth={record['J_actual']:.6f}   "
            f"best so far={record['best_label']} ({record['best_J']:.6f})"
        )
    figure.text(0.055, 0.905, metric, fontsize=10.5, color=color)
    figure.text(
        0.96,
        0.018,
        f"Offline virtual subject: {subject.case_id} • L2 is the strap-equivalent traction-point distance • no robot motion",
        fontsize=8.5,
        color=_GRAY,
        ha="right",
    )
    figure.canvas.draw()
    rgba = np.asarray(figure.canvas.buffer_rgba(), dtype=np.uint8)
    image = Image.fromarray(np.ascontiguousarray(rgba[:, :, :3]))
    plt.close(figure)
    return image


def _render_final_frame(data: Mapping[str, Any], ranges: Mapping[str, tuple[float, float]]) -> Image.Image:
    subject = data["subject"]
    figure = plt.figure(figsize=(12.8, 7.2), dpi=100, facecolor="white")
    axis = figure.add_axes((0.06, 0.09, 0.88, 0.82))
    axis.axis("off")
    axis.text(0.5, 0.93, "SIMULATED PATIENT JOURNEY COMPLETE", ha="center", fontsize=24, weight="bold", color=_DARK)
    axis.text(0.5, 0.84, "Best validated complete trajectory: C1", ha="center", fontsize=16, color=_GREEN)
    values = [1.0] + data["execution"]["actual_J"].astype(float).tolist()
    labels = ["Reference", "C1", "C2", "C3"]
    chart = figure.add_axes((0.13, 0.22, 0.47, 0.48))
    colors = [_GRAY, _GREEN, _BLUE, _ORANGE]
    chart.bar(labels, values, color=colors)
    chart.set_ylim(min(values) - 0.008, 1.004)
    chart.set_ylabel("Whole-trajectory mechanical J")
    chart.set_title("All completed rounds")
    for index, value in enumerate(values):
        chart.text(index, value + 0.001, f"{value:.6f}", ha="center", fontsize=10)
    axis.text(
        0.67,
        0.61,
        (
            f"Reference J     1.000000\n"
            f"Best C1 J       {subject.B2_final_best_validated_J:.6f}\n\n"
            f"Mechanical J reduction\n{100 * subject.reference_improvement:.2f}%\n\n"
            f"Global regret\n{subject.global_regret:.6f}"
        ),
        fontsize=13,
        linespacing=1.45,
        color=_DARK,
        va="top",
    )
    axis.text(
        0.5,
        0.06,
        "Kinematic visualization of frozen offline simulation data • not human, comfort, clinical, safety, or robot evidence",
        ha="center",
        fontsize=10,
        color=_RED,
    )
    figure.canvas.draw()
    rgba = np.asarray(figure.canvas.buffer_rgba(), dtype=np.uint8)
    image = Image.fromarray(np.ascontiguousarray(rgba[:, :, :3]))
    plt.close(figure)
    return image


def generate_leg_rounds_animation(
    artifact_directory: str | Path = SOURCE_ARTIFACT_DIRECTORY,
    *,
    case_id: str = DEFAULT_CASE_ID,
    output_path: str | Path | None = None,
    samples_per_round: int = DEFAULT_SAMPLES_PER_ROUND,
) -> tuple[Path, dict[str, Any]]:
    if isinstance(samples_per_round, bool) or int(samples_per_round) < 3:
        raise ValueError("samples_per_round must be an integer >= 3")
    samples_per_round = int(samples_per_round)
    _style()
    data = _load_case(artifact_directory, case_id)
    records = _round_records(data)
    ranges = _global_ranges(data["trajectories"])
    indices = np.rint(np.linspace(0, 400, samples_per_round)).astype(int)
    frames: list[Image.Image] = []
    durations: list[int] = []
    for record in records:
        for position, sample_index in enumerate(indices):
            frames.append(_render_motion_frame(data, record, int(sample_index), ranges))
            if position == 0:
                durations.append(650)
            elif position == len(indices) - 1:
                durations.append(450)
            else:
                durations.append(75)
    frames.append(_render_final_frame(data, ranges))
    durations.append(2200)
    output = Path(output_path) if output_path is not None else DEFAULT_OUTPUT_DIRECTORY / GIF_NAME
    output.parent.mkdir(parents=True, exist_ok=True)
    frames[0].save(
        output,
        save_all=True,
        append_images=frames[1:],
        duration=durations,
        loop=0,
        optimize=False,
        disposal=2,
    )
    metadata = {
        "visualization_id": "SUPINE_PATIENT_HIP_KNEE_FLEXION_ROUNDS_V1",
        "case_id": case_id,
        "source_formal_manifest_sha256": _sha256(Path(artifact_directory) / "FINAL_METHOD_MANIFEST_V1.json"),
        "round_order": [record["label"] for record in records],
        "round_actual_J": [float(record["J_actual"]) for record in records],
        "samples_per_round": samples_per_round,
        "frame_count": len(frames),
        "duration_ms": int(sum(durations)),
        "resolution_px": [1280, 720],
        "loop": True,
        "kinematic_points": ["hip", "knee", "distal_strap_equivalent_traction_point_L2"],
        "L2_is_anatomical_ankle": False,
        "theta_shank_definition": "q_hip - q_knee",
        "whole_trajectory_trials": True,
        "truth_used_to_create_or_rank_shortlist": False,
        "held_out_final_test_read": False,
        "robot_connected": False,
        "gif_sha256": _sha256(output),
        "generator_source_sha256": _sha256(Path(__file__)),
    }
    return output, metadata


def _guide(metadata: Mapping[str, Any]) -> str:
    return f"""# Simulated leg motion through all finite-validation rounds

`{GIF_NAME}` animates the frozen offline case `{metadata['case_id']}` as a
side-view supine patient on a hospital bed, in this order: Reference → C1 → C2
→ C3 → final measured/virtual-truth selection.

The left panel shows the hip, knee, and distal strap-equivalent traction point
moving through each complete 24 s cycle.  A faint dashed leg is the Reference
pose at the same time during candidate rounds.  The colored trail is the distal
traction-point path.  The right panels show hip and knee angles with a moving
time cursor.

- Frames: {metadata['frame_count']}
- Resolution: 1280×720
- Compressed duration: {metadata['duration_ms'] / 1000:.2f} s
- Round J values: {metadata['round_actual_J']}

L2 is the project-defined strap-equivalent traction-point distance, not an
anatomical ankle.  This is frozen offline simulation evidence and contains no
robot motion or human observation.
"""


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--artifact-directory", type=Path, default=SOURCE_ARTIFACT_DIRECTORY)
    parser.add_argument("--output-directory", type=Path, default=DEFAULT_OUTPUT_DIRECTORY)
    parser.add_argument("--case-id", default=DEFAULT_CASE_ID)
    parser.add_argument("--samples-per-round", type=int, default=DEFAULT_SAMPLES_PER_ROUND)
    arguments = parser.parse_args(argv)
    output, metadata = generate_leg_rounds_animation(
        arguments.artifact_directory,
        case_id=str(arguments.case_id),
        output_path=arguments.output_directory / GIF_NAME,
        samples_per_round=int(arguments.samples_per_round),
    )
    _atomic_bytes(
        arguments.output_directory / METADATA_NAME,
        (json.dumps(metadata, indent=2, sort_keys=True) + "\n").encode("utf-8"),
    )
    _atomic_bytes(
        arguments.output_directory / GUIDE_NAME,
        _guide(metadata).encode("utf-8"),
    )
    print(json.dumps({"gif": str(output), **metadata}, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
