"""Frozen-evidence tests for MYOLEG_VIRTUAL_PATIENT_COHORT_GENERATION_V1.

The expensive MyoLeg replays are not regenerated by normal repository pytest.
These tests independently verify the literal frozen sample, subject identities,
retained replay arrays, scientific scope, and upstream input hashes.
"""

from __future__ import annotations

import ast
import csv
import hashlib
import json
from pathlib import Path

import numpy as np


ROOT = Path(__file__).resolve().parents[1]
ARTIFACTS = (
    ROOT
    / "external_simulation_audits"
    / "myoleg_virtual_patient_cohort_generation_v1"
)
COHORT = (
    ROOT
    / "external_simulation"
    / "cohorts"
    / "myoleg_virtual_patient_cohort_v1"
)
SUBJECTS = COHORT / "subjects"
BUILDER = (
    ROOT
    / "external_simulation"
    / "myoleg_virtual_patient_cohort_generation_v1"
    / "build_cohort.py"
)
DESIGN = ROOT / "external_simulation_audits" / "myoleg_virtual_patient_cohort_design_v1"
RANGES = ROOT / "external_simulation_audits" / "myoleg_cohort_parameter_range_evidence_v1"
MODEL = ROOT / "external_simulation" / "myoleg_supine_rehab_v1" / "myoleg_supine_right_v1.xml"
V2_REFERENCE = (
    ROOT
    / "external_simulation_audits"
    / "myoleg_knee_rom_compatibility_audit_v1"
    / "NATIVE_ROM_REFERENCE_CANDIDATE.csv"
)
TRUTH_SEMANTICS = (
    ROOT
    / "external_simulation_audits"
    / "myoleg_reference_trajectory_replay_v1"
    / "MYOLEG_DYNAMICS_TRUTH_SEMANTICS_V1.json"
)
FROZEN_NOMINAL = TRUTH_SEMANTICS.with_name("SENSITIVITY_REFERENCE_REPLAY.npz")
FORMAL_REFERENCE = ROOT / "reference_release" / "reference_measured_asymmetric_closed_slow.csv"
FORMAL_MANIFEST = ROOT / "config" / "formal_experiment_manifest.json"
COORDINATE_MAPPING = (
    ROOT
    / "external_simulation_audits"
    / "myoleg_supine_hip_knee_rehab_feasibility_v1"
    / "PROJECT_MYOLEG_COORDINATE_MAPPING.json"
)

FROZEN = {
    MODEL: "20e46cd3e372fbcbdddaf7ff6dceae0652e5e9f66237ca573f6612ae4a800b7d",
    V2_REFERENCE: "208a13cef47ff5407348db27dc0a8570e803f9191fbb29b85fabf3fb71012678",
    TRUTH_SEMANTICS: "750d94b59427cdf25cd026192b889a5ba4345e7cb9bdd674434c4a61771c0adc",
    FROZEN_NOMINAL: "ffb389f22ad586a1cbe3f18fbaca9a4bf2cc7964d94336bb5e398a38b64e6cde",
    FORMAL_REFERENCE: "f63bdea2e0d346d73151eedaac73e887f1028c99a6eb15cfc3bc44cfd088a881",
    FORMAL_MANIFEST: "f80a44e24c1b3ce3ffb98f459364883a9798c179f8b7cfa7e05cc9eb401ad441",
    COORDINATE_MAPPING: "83798958fd0b12f5c5314bc32df898f1d6e56d8e224f7673d8aca5c457ce713c",
    DESIGN / "checksums.sha256": "1f307917a08e64dd81e779a88838043cc81cc4dac9a347c1b6aacc3e4b5edfa6",
    RANGES / "checksums.sha256": "492213ea82680efc2457c29b9bdfc82c3af58395347ae2b5bf3f7e69c74fa3c8",
    RANGES / "PROPOSED_PARAMETER_RANGES.json": "10135f17cb0780da586bf466c3ae53b1fb0ed64a86afea5af656c0173cbeb134",
    RANGES / "MYOLEG_VIRTUAL_PATIENT_COHORT_GENERATION_PROTOCOL_V1.json": "94abf249d19e7ec820ba6c24b6be665686b0434379b27c5c281620e10405fc48",
}

FACTORS = (
    "FEMUR_MASS_INERTIA_SCALE",
    "TIBIA_PATELLA_MASS_INERTIA_SCALE",
    "FOOT_COMPLEX_MASS_INERTIA_SCALE",
    "HIP_ONLY_PASSIVE_FP_MAX_SCALE",
    "KNEE_ONLY_PASSIVE_FP_MAX_SCALE",
    "HIP_KNEE_BIARTICULAR_PASSIVE_FP_MAX_SCALE",
)
PRIMARY_BOUNDS = np.asarray(
    [
        [0.88, 1.12],
        [0.87, 1.13],
        [0.82, 1.18],
        [0.95, 1.05],
        [0.95, 1.05],
        [0.95, 1.05],
    ],
    dtype=np.float64,
)
DEV_IDS = tuple(
    f"MYOLEG_VP_{index:03d}"
    for index in (1, 2, 3, 5, 6, 7, 9, 10, 11, 13, 14, 15, 17, 18, 19, 21, 22, 23, 25, 26, 27, 29, 30, 31)
)
HELD_OUT_IDS = tuple(
    f"MYOLEG_VP_{index:03d}" for index in (4, 8, 12, 16, 20, 24, 28, 32)
)


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def read_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as stream:
        return list(csv.DictReader(stream))


def validate_checksums(directory: Path) -> None:
    for line in (directory / "checksums.sha256").read_text(encoding="utf-8").splitlines():
        expected, relative = line.split(maxsplit=1)
        assert sha256(directory / relative.strip()) == expected, relative


def independent_centered_maximin_lhs() -> np.ndarray:
    """Independently repeat the preregistered NumPy PCG64 construction."""
    rng = np.random.Generator(np.random.PCG64(20260830))
    centers = (np.arange(32, dtype=np.float64) + 0.5) / 32.0
    best: np.ndarray | None = None
    best_distance = -np.inf
    best_flat: tuple[float, ...] | None = None
    for _ in range(512):
        candidate = np.column_stack([centers[rng.permutation(32)] for _ in range(6)])
        delta = candidate[:, None, :] - candidate[None, :, :]
        distance = np.sqrt(np.sum(delta * delta, axis=2))
        minimum = float(np.min(distance[np.triu_indices(32, k=1)]))
        flat = tuple(candidate.ravel())
        if minimum > best_distance or (
            minimum == best_distance and (best_flat is None or flat < best_flat)
        ):
            best = candidate.copy()
            best_distance = minimum
            best_flat = flat
    assert best is not None
    return best


def test_required_artifacts_and_recursive_checksums() -> None:
    required = {
        "MYOLEG_VIRTUAL_PATIENT_COHORT_GENERATION_REPORT.md",
        "MYOLEG_VIRTUAL_PATIENT_COHORT_V1_MANIFEST.json",
        "LHS_UNIT_CUBE_MATRIX.csv",
        "SUBJECT_PARAMETER_MATRIX.csv",
        "SUBJECT_SPLIT.csv",
        "SAMPLING_FREEZE_MANIFEST.json",
        "SUBJECT_REFERENCE_NORMALIZATION.csv",
        "SUBJECT_INTEGRITY_RESULTS.csv",
        "COHORT_REFERENCE_RESPONSE_SUMMARY.csv",
        "COHORT_PARAMETER_RESPONSE_DIAGNOSTICS.csv",
        "COHORT_COVERAGE_AUDIT.json",
        "RUNTIME_BENCHMARK.json",
        "metadata.json",
        "checksums.sha256",
    }
    assert required == {path.name for path in ARTIFACTS.iterdir() if path.is_file()}
    validate_checksums(ARTIFACTS)
    validate_checksums(COHORT)


def test_all_frozen_inputs_and_range_evidence_remain_unchanged() -> None:
    for path, expected in FROZEN.items():
        assert sha256(path) == expected, path
    validate_checksums(DESIGN)
    validate_checksums(RANGES)
    metadata = read_json(ARTIFACTS / "metadata.json")
    assert metadata["input_sha256_before"] == metadata["input_sha256_after"]
    formal = read_json(FORMAL_MANIFEST)
    assert formal["rom_protocol_version"] == "ROM_PROTOCOL_V2"
    assert formal["theta_shank_definition"] == "q_hip - q_knee"


def test_literal_lhs_is_deterministic_centered_stratified_and_unique() -> None:
    rows = read_csv(ARTIFACTS / "LHS_UNIT_CUBE_MATRIX.csv")
    unit_columns = tuple(f"u_{index}_{factor}" for index, factor in enumerate(FACTORS, 1))
    matrix = np.asarray([[float(row[column]) for column in unit_columns] for row in rows])
    assert matrix.shape == (32, 6)
    assert np.array_equal(matrix, independent_centered_maximin_lhs())
    assert np.unique(matrix, axis=0).shape[0] == 32
    expected_centers = (np.arange(32, dtype=np.float64) + 0.5) / 32.0
    for column in matrix.T:
        assert np.array_equal(np.sort(column), expected_centers)
    audit = read_json(ARTIFACTS / "COHORT_COVERAGE_AUDIT.json")["overall_lhs"]
    assert audit["duplicate_row_count"] == 0
    assert audit["all_dimensions_centered_stratified"] is True


def test_transformed_matrix_uses_only_frozen_primary_bounds() -> None:
    unit_rows = read_csv(ARTIFACTS / "LHS_UNIT_CUBE_MATRIX.csv")
    parameter_rows = read_csv(ARTIFACTS / "SUBJECT_PARAMETER_MATRIX.csv")
    unit_columns = tuple(f"u_{index}_{factor}" for index, factor in enumerate(FACTORS, 1))
    unit = np.asarray([[float(row[column]) for column in unit_columns] for row in unit_rows])
    physical = np.asarray([[float(row[factor]) for factor in FACTORS] for row in parameter_rows])
    expected = PRIMARY_BOUNDS[:, 0] + unit * (PRIMARY_BOUNDS[:, 1] - PRIMARY_BOUNDS[:, 0])
    assert np.array_equal(physical, expected)
    assert np.all(physical >= PRIMARY_BOUNDS[:, 0])
    assert np.all(physical <= PRIMARY_BOUNDS[:, 1])
    manifest = read_json(ARTIFACTS / "MYOLEG_VIRTUAL_PATIENT_COHORT_V1_MANIFEST.json")
    assert manifest["extended_ranges_used"] is False


def test_exact_split_is_frozen_and_nominal_is_separate() -> None:
    manifest = read_json(ARTIFACTS / "MYOLEG_VIRTUAL_PATIENT_COHORT_V1_MANIFEST.json")
    rows = read_csv(ARTIFACTS / "SUBJECT_SPLIT.csv")
    assert manifest["cohort_size"] == 32
    assert tuple(manifest["development_subject_ids"]) == DEV_IDS
    assert tuple(manifest["held_out_subject_ids"]) == HELD_OUT_IDS
    assert sum(row["split"] == "DEVELOPMENT" for row in rows) == 24
    assert sum(row["split"] == "HELD_OUT" for row in rows) == 8
    ids = {row["subject_id"] for row in rows}
    assert ids == set(DEV_IDS) | set(HELD_OUT_IDS)
    assert "SUBJECT_NOMINAL_CONTROL" not in ids
    assert manifest["nominal_control_counted_in_cohort"] is False
    assert manifest["replacement_sampling_used"] is False


def test_all_subject_identities_and_scheme_a_only_deltas_are_retained() -> None:
    manifest = read_json(ARTIFACTS / "MYOLEG_VIRTUAL_PATIENT_COHORT_V1_MANIFEST.json")
    assert len(manifest["subjects"]) == 32
    model_fingerprints = set()
    allowed_body_fields = {"body_mass", "body_inertia"}
    allowed_actuator_fields = {
        "actuator_gainprm_7_fpmax",
        "actuator_biasprm_7_fpmax",
    }
    for subject in manifest["subjects"]:
        directory = SUBJECTS / subject["subject_id"]
        delta = read_json(directory / "model_delta.json")
        metadata = read_json(directory / "metadata.json")
        assert tuple(delta["factor_order"]) == FACTORS
        assert delta["factor_values"] == subject["factor_values"]
        assert delta["unit_cube_vector"] == subject["unit_cube_vector"]
        assert delta["inertia_scaling_is_modeling_approximation"] is True
        assert delta["base_model_sha256"] == FROZEN[MODEL]
        assert delta["cohort_protocol_sha256"] == FROZEN[RANGES / "MYOLEG_VIRTUAL_PATIENT_COHORT_GENERATION_PROTOCOL_V1.json"]
        for change in delta["modifications"]:
            assert change["factor_id"] in FACTORS
            if change["object_type"] == "body":
                assert set(change["fields"]) <= allowed_body_fields
                assert change["body_ipos_com_unchanged"] is True
            else:
                assert change["object_type"] == "actuator"
                assert set(change["fields"]) <= allowed_actuator_fields
        checks = metadata["structure"]["checks"]
        assert all(checks.values())
        assert metadata["structure"]["dimensions"]["nu"] == 80
        assert metadata["structure"]["dimensions"]["ntendon"] == 80
        assert metadata["structure"]["pass"] is True
        model_fingerprints.add(metadata["generated_model_fingerprint_sha256"])
    assert len(model_fingerprints) == 32


def test_all_reference_replays_are_complete_finite_and_normalized() -> None:
    integrity = read_csv(ARTIFACTS / "SUBJECT_INTEGRITY_RESULTS.csv")
    normalization = read_csv(ARTIFACTS / "SUBJECT_REFERENCE_NORMALIZATION.csv")
    assert len(integrity) == len(normalization) == 32
    assert all(row["subject_integrity"] == "PASS" for row in integrity)
    assert all(row["replacement_sample"] == "False" for row in integrity)
    assert all(row["subject_specific_reference_normalization"] == "PASS" for row in normalization)
    assert all(row["nominal_denominator_used"] == "False" for row in normalization)
    for row in normalization:
        assert float(row["subject_reference_tau_hip_rms_nm"]) > 0.0
        assert float(row["subject_reference_tau_knee_rms_nm"]) > 0.0
        assert abs(float(row["j_truth_reference"]) - 1.0) <= 1.0e-12
        replay_path = SUBJECTS / row["subject_id"] / "reference_replay_truth.npz"
        with np.load(replay_path, allow_pickle=False) as replay:
            assert replay["time_s"].shape == (401,)
            assert replay["tau_truth_nm"].shape == (401, 2)
            assert replay["actuator_force_n"].shape == (401, 80)
            assert replay["tendon_length_m"].shape == (401, 80)
            assert replay["time_s"][0] == 0.0
            assert replay["time_s"][-1] == 24.0
            assert all(np.isfinite(replay[name]).all() for name in replay.files if replay[name].dtype.kind in "fciu")


def test_nominal_control_is_an_exact_copy_of_frozen_nominal_replay() -> None:
    nominal_path = COHORT / "nominal_control" / "reference_replay_truth.npz"
    assert sha256(nominal_path) == sha256(FROZEN_NOMINAL) == FROZEN[FROZEN_NOMINAL]
    with np.load(nominal_path, allow_pickle=False) as actual, np.load(FROZEN_NOMINAL, allow_pickle=False) as frozen:
        assert actual.files == frozen.files
        assert all(np.array_equal(actual[name], frozen[name]) for name in frozen.files)
    metadata = read_json(COHORT / "nominal_control" / "metadata.json")
    assert metadata["subject_id"] == "SUBJECT_NOMINAL_CONTROL"
    assert metadata["cohort_member"] is False
    exact = metadata["exact_array_match_to_frozen_nominal"]
    assert exact["exact"] is True
    assert exact["compared_array_count"] == 49
    assert exact["mismatched_keys"] == exact["missing_or_extra_keys"] == []


def test_post_freeze_diagnostics_never_modify_subjects_or_ranges() -> None:
    diagnostics = read_csv(ARTIFACTS / "COHORT_PARAMETER_RESPONSE_DIAGNOSTICS.csv")
    assert len(diagnostics) == 24
    assert all(row["analysis_role"] == "POST_FREEZE_DESCRIPTIVE_ONLY" for row in diagnostics)
    assert all(row["used_to_modify_ranges_sampling_or_subjects"] == "False" for row in diagnostics)
    coverage = read_json(ARTIFACTS / "COHORT_COVERAGE_AUDIT.json")
    assert coverage["learner_performance_compared"] is False
    assert coverage["development"]["count"] == 24
    assert coverage["held_out"]["count"] == 8


def test_stage_scope_excludes_landscape_learning_bo_and_robot_access() -> None:
    metadata = read_json(ARTIFACTS / "metadata.json")
    assert metadata["candidate_landscape_generated"] is False
    assert metadata["five_parameter_fit"] is False
    assert metadata["nn_trained"] is False
    assert metadata["pinn_trained"] is False
    assert metadata["bo_run"] is False
    assert metadata["robot_connected"] is False
    assert metadata["hardware_accessed"] is False
    assert metadata["next_stage_executed"] is False
    tree = ast.parse(BUILDER.read_text(encoding="utf-8"))
    imports = {
        alias.name
        for node in ast.walk(tree)
        if isinstance(node, (ast.Import, ast.ImportFrom))
        for alias in node.names
    }
    forbidden = {"hardware", "control", "sklearn", "torch", "tensorflow", "pymc", "gpytorch"}
    assert not any(name.split(".")[0] in forbidden for name in imports)


def test_manifest_and_literal_matrices_are_frozen_by_sha() -> None:
    metadata = read_json(ARTIFACTS / "metadata.json")
    manifest_path = ARTIFACTS / "MYOLEG_VIRTUAL_PATIENT_COHORT_V1_MANIFEST.json"
    assert metadata["manifest_sha256"] == sha256(manifest_path)
    assert metadata["sampling_freeze_manifest_sha256"] == sha256(
        ARTIFACTS / "SAMPLING_FREEZE_MANIFEST.json"
    )
    manifest = read_json(manifest_path)
    assert manifest["all_subject_integrity_pass"] is True
    assert manifest["all_subject_specific_reference_normalization_pass"] is True
    assert manifest["outcome"] == "MYOLEG_VIRTUAL_PATIENT_COHORT_V1_VALID_WITH_LIMITATIONS"
    assert manifest["candidate_landscape_generated"] is False
